export const BASE_URL = import.meta.env.VITE_API_URL;

const API = {
    BASE_URL: BASE_URL,
    LOGIN: BASE_URL + '/api/login',
    CHANGE_PASSWORD: BASE_URL + '/api/v1/password/change',
    PERMISSIONS: BASE_URL + '/api/v1/permissions/',
    SYNC_USERS_PERMISSIONS: BASE_URL + '/api/v1/syncUserPermissions/',
    ROLES: BASE_URL + '/api/v1/roles/',
    USERS: BASE_URL + '/api/v1/users/',
    BOOKS: BASE_URL + '/api/v1/books/',
    CHARGES: BASE_URL + '/api/v1/charges/',
    PRODUCTS: BASE_URL + '/api/v1/products/',
    ADD_PRODUCTS: BASE_URL + '/api/v1/addProduct/',
    PRODUCTS_STATUS: BASE_URL + '/api/v1/products/{product}/updateStatus',
    APPLICANTS: BASE_URL + '/api/v1/applicants/',
    APPLICANTS_STATUS: BASE_URL + '/api/v1/applicants/updateStatus',
    APPLICANTS_PRODUCTS_SYNC: BASE_URL + '/api/v1/applicants/{applicant}/products/sync',
    APPLICANTS_ASSIGN_CREDIT_LIMIT: BASE_URL + '/api/v1/applicants/{applicant}/assignCreditLimit',
    APPLICANTS_ASSIGN_FINANCING_POLICY: BASE_URL + '/api/v1/applicants/{applicant}/assignFinancingPolicy',
    ADDAPPLICANTS: BASE_URL + '/api/v1/addApplicant/',
    APPLICATIONS: BASE_URL + '/api/v1/applications',
    REPAYMENTS: BASE_URL + '/api/v1/repayments',
    REFRESH_OFAC_NACTA: BASE_URL + '/api/v1/refreshOfacNacta',
    EXPORT_APPLICATIONS: BASE_URL + '/api/v1/application/export',
    EXPORT_REPAYMENTS: BASE_URL + '/api/v1/repayment/export',
    DASHBOARD_STATS: BASE_URL + '/api/v1/dashboard/stats',
    OVERDUE_LOANS: BASE_URL + '/api/v1/reports/overdue-loans',
    EXPORT_DELINQUENT_APPLICATIONS: BASE_URL + '/api/v1/reports/export-overdue-loans',
    APPLICATIONS_INITIATE: BASE_URL + '/api/v1/applications/initiate',
    APPLICATIONS_CALCULATE: BASE_URL + '/api/v1/applications/calculate',
    APPLICATIONS_LOAN_DETAILS: BASE_URL + '/api/v1/applicantLoanDetails/',
    PAY_INSTALLMENT: BASE_URL + '/api/v1/repayment/pay-installment',
}

export default API;
